// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ProtoBufPackage;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface C2S_GetStudentInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Xsjm.Logic.Protocols.C2S_GetStudentInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    java.util.List<ProtoBufPackage.PersonProto.Person> 
        getPersonList();
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    ProtoBufPackage.PersonProto.Person getPerson(int index);
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    int getPersonCount();
  }
  /**
   * Protobuf type {@code Xsjm.Logic.Protocols.C2S_GetStudentInfo}
   */
  public static final class C2S_GetStudentInfo extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:Xsjm.Logic.Protocols.C2S_GetStudentInfo)
      C2S_GetStudentInfoOrBuilder {
    // Use C2S_GetStudentInfo.newBuilder() to construct.
    private C2S_GetStudentInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2S_GetStudentInfo(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final C2S_GetStudentInfo defaultInstance;
    public static C2S_GetStudentInfo getDefaultInstance() {
      return defaultInstance;
    }

    public C2S_GetStudentInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private C2S_GetStudentInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                person_ = new java.util.ArrayList<ProtoBufPackage.PersonProto.Person>();
                mutable_bitField0_ |= 0x00000008;
              }
              person_.add(input.readMessage(ProtoBufPackage.PersonProto.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<C2S_GetStudentInfo> PARSER =
        new com.google.protobuf.AbstractParser<C2S_GetStudentInfo>() {
      public C2S_GetStudentInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_GetStudentInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_GetStudentInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int PERSON_FIELD_NUMBER = 4;
    private java.util.List<ProtoBufPackage.PersonProto.Person> person_;
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    public java.util.List<ProtoBufPackage.PersonProto.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    public java.util.List<? extends ProtoBufPackage.PersonProto.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    public ProtoBufPackage.PersonProto.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
     */
    public ProtoBufPackage.PersonProto.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      age_ = 0;
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(4, person_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, person_.get(i));
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_GetStudentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoBufPackage.StudentProto.C2S_GetStudentInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Xsjm.Logic.Protocols.C2S_GetStudentInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProtoBufPackage.StudentProto.C2S_GetStudentInfo, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Xsjm.Logic.Protocols.C2S_GetStudentInfo)
        ProtoBufPackage.StudentProto.C2S_GetStudentInfoOrBuilder {
      // Construct using ProtoBufPackage.StudentProto.C2S_GetStudentInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        person_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public ProtoBufPackage.StudentProto.C2S_GetStudentInfo getDefaultInstanceForType() {
        return ProtoBufPackage.StudentProto.C2S_GetStudentInfo.getDefaultInstance();
      }

      public ProtoBufPackage.StudentProto.C2S_GetStudentInfo build() {
        ProtoBufPackage.StudentProto.C2S_GetStudentInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoBufPackage.StudentProto.C2S_GetStudentInfo buildPartial() {
        ProtoBufPackage.StudentProto.C2S_GetStudentInfo result = new ProtoBufPackage.StudentProto.C2S_GetStudentInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          person_ = java.util.Collections.unmodifiableList(person_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.person_ = person_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(ProtoBufPackage.StudentProto.C2S_GetStudentInfo other) {
        if (other == ProtoBufPackage.StudentProto.C2S_GetStudentInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (!other.person_.isEmpty()) {
          if (person_.isEmpty()) {
            person_ = other.person_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePersonIsMutable();
            person_.addAll(other.person_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBufPackage.StudentProto.C2S_GetStudentInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBufPackage.StudentProto.C2S_GetStudentInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        
        return this;
      }

      private java.util.List<ProtoBufPackage.PersonProto.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          person_ = new java.util.ArrayList<ProtoBufPackage.PersonProto.Person>(person_);
          bitField0_ |= 0x00000008;
         }
      }

      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public java.util.List<ProtoBufPackage.PersonProto.Person> getPersonList() {
        return java.util.Collections.unmodifiableList(person_);
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public int getPersonCount() {
        return person_.size();
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public ProtoBufPackage.PersonProto.Person getPerson(int index) {
        return person_.get(index);
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder setPerson(
          int index, ProtoBufPackage.PersonProto.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder setPerson(
          int index, ProtoBufPackage.PersonProto.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder addPerson(ProtoBufPackage.PersonProto.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.add(value);

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder addPerson(
          int index, ProtoBufPackage.PersonProto.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder addPerson(
          ProtoBufPackage.PersonProto.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder addPerson(
          int index, ProtoBufPackage.PersonProto.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends ProtoBufPackage.PersonProto.Person> values) {
        ensurePersonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, person_);

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder clearPerson() {
        person_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);

        return this;
      }
      /**
       * <code>repeated .Xsjm.Logic.Protocols.Person person = 4;</code>
       */
      public Builder removePerson(int index) {
        ensurePersonIsMutable();
        person_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:Xsjm.Logic.Protocols.C2S_GetStudentInfo)
    }

    static {
      defaultInstance = new C2S_GetStudentInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Xsjm.Logic.Protocols.C2S_GetStudentInfo)
  }

  public interface C2S_LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Xsjm.Logic.Protocols.C2S_Login)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 PID = 1 [default = 1];</code>
     */
    boolean hasPID();
    /**
     * <code>optional int32 PID = 1 [default = 1];</code>
     */
    int getPID();

    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    boolean hasAuthInfo();
    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    java.lang.String getAuthInfo();
    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getAuthInfoBytes();

    /**
     * <code>optional string Platform = 3;</code>
     */
    boolean hasPlatform();
    /**
     * <code>optional string Platform = 3;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>optional string Platform = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();
  }
  /**
   * Protobuf type {@code Xsjm.Logic.Protocols.C2S_Login}
   */
  public static final class C2S_Login extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:Xsjm.Logic.Protocols.C2S_Login)
      C2S_LoginOrBuilder {
    // Use C2S_Login.newBuilder() to construct.
    private C2S_Login(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2S_Login(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final C2S_Login defaultInstance;
    public static C2S_Login getDefaultInstance() {
      return defaultInstance;
    }

    public C2S_Login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private C2S_Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pID_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              authInfo_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              platform_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<C2S_Login> PARSER =
        new com.google.protobuf.AbstractParser<C2S_Login>() {
      public C2S_Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_Login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_Login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PID_FIELD_NUMBER = 1;
    private int pID_;
    /**
     * <code>optional int32 PID = 1 [default = 1];</code>
     */
    public boolean hasPID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 PID = 1 [default = 1];</code>
     */
    public int getPID() {
      return pID_;
    }

    public static final int AUTHINFO_FIELD_NUMBER = 2;
    private java.lang.Object authInfo_;
    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    public boolean hasAuthInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    public java.lang.String getAuthInfo() {
      java.lang.Object ref = authInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string AuthInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAuthInfoBytes() {
      java.lang.Object ref = authInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 3;
    private java.lang.Object platform_;
    /**
     * <code>optional string Platform = 3;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string Platform = 3;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platform_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Platform = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      pID_ = 1;
      authInfo_ = "";
      platform_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAuthInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPlatformBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPlatformBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoBufPackage.StudentProto.C2S_Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoBufPackage.StudentProto.C2S_Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Xsjm.Logic.Protocols.C2S_Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProtoBufPackage.StudentProto.C2S_Login, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:Xsjm.Logic.Protocols.C2S_Login)
        ProtoBufPackage.StudentProto.C2S_LoginOrBuilder {
      // Construct using ProtoBufPackage.StudentProto.C2S_Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pID_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        authInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public ProtoBufPackage.StudentProto.C2S_Login getDefaultInstanceForType() {
        return ProtoBufPackage.StudentProto.C2S_Login.getDefaultInstance();
      }

      public ProtoBufPackage.StudentProto.C2S_Login build() {
        ProtoBufPackage.StudentProto.C2S_Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoBufPackage.StudentProto.C2S_Login buildPartial() {
        ProtoBufPackage.StudentProto.C2S_Login result = new ProtoBufPackage.StudentProto.C2S_Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pID_ = pID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.authInfo_ = authInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.platform_ = platform_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(ProtoBufPackage.StudentProto.C2S_Login other) {
        if (other == ProtoBufPackage.StudentProto.C2S_Login.getDefaultInstance()) return this;
        if (other.hasPID()) {
          setPID(other.getPID());
        }
        if (other.hasAuthInfo()) {
          bitField0_ |= 0x00000002;
          authInfo_ = other.authInfo_;
          
        }
        if (other.hasPlatform()) {
          bitField0_ |= 0x00000004;
          platform_ = other.platform_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBufPackage.StudentProto.C2S_Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBufPackage.StudentProto.C2S_Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pID_ = 1;
      /**
       * <code>optional int32 PID = 1 [default = 1];</code>
       */
      public boolean hasPID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 PID = 1 [default = 1];</code>
       */
      public int getPID() {
        return pID_;
      }
      /**
       * <code>optional int32 PID = 1 [default = 1];</code>
       */
      public Builder setPID(int value) {
        bitField0_ |= 0x00000001;
        pID_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 PID = 1 [default = 1];</code>
       */
      public Builder clearPID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pID_ = 1;
        
        return this;
      }

      private java.lang.Object authInfo_ = "";
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public boolean hasAuthInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public java.lang.String getAuthInfo() {
        java.lang.Object ref = authInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            authInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAuthInfoBytes() {
        java.lang.Object ref = authInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public Builder setAuthInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authInfo_ = value;
        
        return this;
      }
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public Builder clearAuthInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authInfo_ = getDefaultInstance().getAuthInfo();
        
        return this;
      }
      /**
       * <code>optional string AuthInfo = 2;</code>
       */
      public Builder setAuthInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authInfo_ = value;
        
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <code>optional string Platform = 3;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string Platform = 3;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platform_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Platform = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Platform = 3;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        platform_ = value;
        
        return this;
      }
      /**
       * <code>optional string Platform = 3;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000004);
        platform_ = getDefaultInstance().getPlatform();
        
        return this;
      }
      /**
       * <code>optional string Platform = 3;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        platform_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Xsjm.Logic.Protocols.C2S_Login)
    }

    static {
      defaultInstance = new C2S_Login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Xsjm.Logic.Protocols.C2S_Login)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
